### PR TITLE
Corrected typos in the references

### PR DESCRIPTION
**Pull request by star1327p**

### CODE REVIEW

**Comment by fverac** [comment]
Thanks for the typo corrections! Can you update your branch to include the latest changes from main? Then I can approve the PR

**Review by fverac — APPROVED** [review]

**Comment by star1327p** [comment]
@fverac I have updated the branch to include the latest changesfrom main. But the DCO check failed probably because I am using the web version.

**Comment by fverac** [comment]
> @fverac I have updated the branch to include the latest changesfrom main. But the DCO check failed probably because I am using the web version.

Yes, I see that. I believe if you should follow the instructions in the "Details" link next to the DCO check failure it should walk you through how to retroactively sign off on your commits.

**Comment by star1327p** [comment]
> > @fverac I have updated the branch to include the latest changesfrom main. But the DCO check failed probably because I am using the web version.
> 
> Yes, I see that. I believe if you follow the instructions in the "Details" link next to the DCO check failure it should walk you through how to retroactively sign off on your commits.

@fverac I have fixed the DCO issue, and now the DCO check has succeeded.

**Pull request merged**
